import { BallotFlow } from "@/components/BallotFlow";
import { ContinuityIssueCard } from "@/components/ContinuityIssueCard";
import { CreatorApprovalPreview } from "@/components/CreatorApprovalPreview";
import { MovieConceptCard } from "@/components/MovieConceptCard";
import { ResultsPreview } from "@/components/ResultsPreview";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteHeader } from "@/components/SiteHeader";
import { WorkflowSteps } from "@/components/WorkflowSteps";
import { movieConcepts } from "@/data/demo-data";
export default function Home(){return <div id="top" className="site-shell"><SiteHeader/><main><section className="hero"><p className="eyebrow">Audience-driven story development</p><h1>The audience finds the spark. The creator makes the movie.</h1><p className="hero-copy">Viewers Cut turns curated creative choices into a creator-approved direction for fictional movie stories.</p><div className="hero-actions"><a className="button" href="#ballot">Start Voting</a><a className="button button-quiet" href="#how-it-works">See How It Works</a></div><p className="demo-disclaimer">All current projects, vote counts, and results are fictional demo content.</p></section><section className="section concepts" id="discover"><div className="section-heading"><p className="eyebrow">Featured fictional concepts</p><h2>Three stories, waiting for a direction.</h2></div><div className="concept-grid">{movieConcepts.map(concept=><MovieConceptCard concept={concept} key={concept.id}/>)}</div></section><BallotFlow/><WorkflowSteps/><ResultsPreview/><CreatorApprovalPreview/><section className="section continuity"><div className="section-heading"><p className="eyebrow">Continuity review preview</p><h2>Keep every story detail in focus.</h2></div><div className="issue-grid"><ContinuityIssueCard severity="Needs review" title="Prop contradiction" text="Fictional example: a brass key returns after it was already surrendered."/><ContinuityIssueCard severity="Question" title="Character knowledge gap" text="Fictional example: a clue is recognized before it is introduced."/><ContinuityIssueCard severity="Needs review" title="Timeline inconsistency" text="Fictional example: a scene crosses midnight twice."/></div></section></main><SiteFooter/></div>}
